### ISSUE TITLE
Unable to cd into restrictive SMB share

### ISSUE THREAD

**Issue by ypid** [icewind1991/SMB#51]
Dear maintainers

Seems I just hit a rare corner case when trying to access a directory in a SMB/CIFS share.
I am reporting against this library because I think this is where this can be fixed. If I should report downstream instead, please say so.

### Preface

I expect that the problem is related to this behavior of `smbclient`:

```
$ # Tested with both:
$ smbclient -V
Version 4.2.10-Debian

$ smbclient -V
Version 4.4.5-Debian

$ smbclient //share.example.org/user/ypid -U ypid
Enter ypid's password:
Domain=[example.org] OS=[Windows 5.0] Server=[Windows 2000 LAN Manager]
tree connect failed: NT_STATUS_BAD_NETWORK_NAME

$ smbclient //share.example.org/user -U ypid
Enter ypid's password:
Domain=[example.org] OS=[Windows 5.0] Server=[Windows 2000 LAN Manager]
smb: \> ls
NT_STATUS_ACCESS_DENIED listing \*
smb: \> cd ypid
smb: \ypid\> pwd
Current directory is \\share.example.org\user\ypid\
smb: \ypid\> ls
  [expected output]

$ smbclient //share.example.org/user -U ypid --directory ypid
Enter ypid's password:
Domain=[example.org] OS=[Windows 5.0] Server=[Windows 2000 LAN Manager]
smb: \ypid\> ls
  [expected output]
```

#### Refs

* http://www.jeffarnold.net/bad_smbclient/ ([cache](https://webcache.googleusercontent.com/search?q=cache:sqjGyOUXp6IJ:www.jeffarnold.net/bad_smbclient/+&cd=1&hl=de&ct=clnk&gl=de))
* https://askubuntu.com/questions/749070/copy-file-with-smbclient-and-path-to-directory/761987#761987
* https://www.administrator.de/frage/samba-nt-status-bad-network-name-zugriff-52687.html

### Steps to reproduce

1. Setup a Samba or Windows File server which behaves as described above.
2. Setup ownCloud and create an external SMB storage for the above share.
3. Try to open the share using the files app.

### Expected behaviour

The directory’s content of the share should be shown.

### Actual behaviour

```
External mount error

There was an error with message: Empty response from the server. Do you want to review mount point config in admin settings page?
```

### Server configuration
**Operating system**:

Debian GNU/Linux 8.5 (jessie)

**Web server:**

nginx-full: 1.6.2-5+deb8u2+b1

**Database:**

mariadb-server: Installed: 10.0.26-0+deb8u1

**PHP version:**
php5-fpm: Installed: 5.6.24+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.4.1
and/or
ownCloud 9.1.0.15

**Updated from an older ownCloud or fresh install:**
Both

**Where did you install ownCloud from:**

Setup steps fully documented by [DebOps](https://debops.org/) and the [debops.owncloud](https://github.com/debops/ansible-owncloud/) Ansible role (as of [0d3edb04](https://github.com/debops/ansible-owncloud/pull/44/commits/0d3edb04396f9cbdaa2aaaf186e83548faf00548) included in https://github.com/debops/ansible-owncloud/pull/44).

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- Application to check
	- EXCEPTION
		- Exception
		- App not found

Raw output
==========
Array
(
    [Application to check] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => Exception
                    [message] => App not found
                )

        )

)
```

and from the CLI:

```
$ occ integrity:check-app
  - EXCEPTION:
    - class: Exception
    - message: App not found
$ occ integrity:check-core

$
```

Off-topic: Any idea about that?

**List of activated apps:**

```
$ occ app:list
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - files_antivirus
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.org"
        ],
        "datadirectory": "\/media\/data\/owncloud",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.0.4.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "logdateformat": "Y-m-d H:i:s.u",
        "loglevel": 2,
        "instanceid": "something",
        "ldapIgnoreNamingRules": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": "6379"
        },
        "skeletondirectory": "",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "tempdirectory": "\/media\/data\/owncloud_temp"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

smb

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Problem occurs with ldap or/and local database only.

### Client configuration
firefox-esr: 45.3.0esr-1~deb8u1

**Operating system:**
Debian GNU/Linux 8.5 (jessie)

#### Web server error log

Seems irrelevant. Only: `GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json`

#### ownCloud log (data/owncloud.log)

```json
{
  "reqId": "arIGi/aZmUHbaSzNBfWU",
  "remoteAddr": "::ffff:10.245.1.1",
  "app": "files_external",
  "message": "Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Invalid login\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/apps\\/files_external\\/lib\\/smb.php(157): OC\\\\Files\\\\Storage\\\\SMB->getFileInfo('')\\n#1 \\/var\\/www\\/owncloud\\/lib\\/private\\/files\\/storage\\/common.php(434): OC\\\\Files\\\\Storage\\\\SMB->stat('')\\n#2 \\/var\\/www\\/owncloud\\/apps\\/files_external\\/lib\\/smb.php(391): OC\\\\Files\\\\Storage\\\\Common->test()\\n#3 \\/var\\/www\\/owncloud\\/apps\\/files_external\\/lib\\/config.php(231): OC\\\\Files\\\\Storage\\\\SMB->test(false, true)\\n#4 \\/var\\/www\\/owncloud\\/apps\\/files_external\\/controller\\/storagescontroller.php(258): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false, true)\\n#5 \\/var\\/www\\/owncloud\\/apps\\/files_external\\/controller\\/globalstoragescontroller.php(181): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_external\\\\Lib\\\\StorageConfig), true)\\n#6 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(6, 'home', 'smb', 'password::sessi...', Array, Array, Array, Array, 100, true)\\n#7 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/http\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#9 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#10 \\/var\\/www\\/owncloud\\/lib\\/private\\/appframework\\/routing\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('GlobalStoragesC...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\/var\\/www\\/owncloud\\/lib\\/private\\/route\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\/var\\/www\\/owncloud\\/lib\\/base.php(907): OC\\\\Route\\\\Router->match('\\/apps\\/files_ext...')\\n#14 \\/var\\/www\\/owncloud\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/apps\\/files_external\\/lib\\/smb.php\",\"Line\":119}",
  "level": 3,
  "time": "2016-08-09 14:42:19.736100",
  "method": "PUT",
  "url": "/apps/files_external/globalstorages/6",
  "user": "admin"
}
```

#### Browser log

Seems irrelevant. Omitted

### Additional testing

I tested with `php-smbclient`:

```
apt-cache policy php-smbclient
php-smbclient:
  Installed: 0.8.0-3
  Candidate: 0.8.0-3
  Version table:
 *** 0.8.0-3 0
         50 http://httpredir.debian.org/debian/ stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

as well as with [latest master](https://github.com/icewind1991/SMB/commit/2a101e73bc6a354eab8c1dd6f7d113af63e255e8) of [the SMB library](https://github.com/icewind1991/SMB) by copying the source into the source directory of ownCloud 9.1.

If you need anything else feel free to ask :wink:

**Comment by ypid** [comment]
Note that this should be easy to fix as it works with the `--directory` option: `$ smbclient //share.example.org/user -U ypid --directory ypid`
